# Generated by Django 5.2.1 on 2025-05-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Вставьте ссылку на видео с YouTube', null=True, verbose_name='Ссылка на YouTube видео'),
        ),
    ]
