# Generated by Django 5.2.1 on 2025-05-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_review_options_newsarticle_youtube_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='review',
            name='response',
        ),
    ]
