# Generated by Django 5.2.1 on 2025-09-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='certificate',
            field=models.TextField(blank=True, null=True, verbose_name='<UNK> <UNK>'),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='<UNK> <UNK>'),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='requisites',
            field=models.TextField(blank=True, null=True, verbose_name='<UNK> <UNK>'),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='<UNK> <UNK>'),
        ),
    ]
