# Generated by Django 5.2.1 on 2025-09-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_aboutcompany_certificate_aboutcompany_history_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='banners/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('website_url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='certificate',
            field=models.TextField(blank=True, null=True, verbose_name='Сертификат'),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='История'),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='requisites',
            field=models.TextField(blank=True, null=True, verbose_name='Реквизиты'),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Видео'),
        ),
    ]
